config/routes.rb
Rails.application.routes.draw do
  get 'categories/new'
  get 'categories/create'
  resources :products do
    post '/update_quantity', to: 'products#update_quantity'
    collection do
      get '/products', to: 'products#product', as: 'products'
      get 'products/products', to: 'products#next_batch', as: 'products_products'

    end
    resources :similar_products
    collection do
      get 'filtered'
    end
  end 
  resources :carts do
    resources :lineitems
  end
  resources :carts do
    post 'add_to_cart', on: :collection
  delete 'remove_item', on: :member
  end
  resources :lineitems do
    patch 'increase_quantity', on: :member
    patch 'decrease_quantity', on: :member
    patch 'increase_stk', on: :member
    patch 'decrease_stk', on: :member
  end
  resources :categories 


  resources :orders do
    get '/status', to: 'orders#status', as: 'status'
  end
  resources :addresses

  devise_for :users, controllers: { registrations: 'users/registrations',
    sessions: 'users/sessions'}
  devise_scope :user do
    get '/verify_user', to: 'devise/sessions#verify'
  end

  get 'enable_otp_show_qr', to: 'users#enable_otp_show_qr', as: 'enable_otp_show_qr'
  post 'enable_otp_verify', to: 'users#enable_otp_verify', as: 'enable_otp_verify'

  get 'users/otp', to: 'users#show_otp', as: 'user_otp'
  post 'users/otp', to: 'users#verify_otp', as: 'verify_user_otp'
  post 'verify_otp', to: 'users/sessions#verify_otp'
  
  root to: "products#index"
  resources :payments, only: [:create, :show, :new] do
    collection do
      post '/create_payment', to: 'payments#create_payment'
      post 'payment_callback'
      get '/success', to: 'payments#success', as: 'success'
      get '/offline_payment', to: 'payments#offline_payment', as: 'offline_payment'
      get '/invoice_print', to: 'payments#invoice_print', as: 'invoice_print'
      get 'download_pdf'
      post '/update_status', to: 'payments#update_status'
    end
  end
  post '/payments/create_payment/:order_id', to: 'payments#create_payment', as: 'create_payment'
  resources :razorpay, only: [:create_payment, :payment_callback]
  resources :users do
     collection do
       get 'user'
       get 'userinfo'
     end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :two_factor_authenticatable
  has_many :orders
  has_many :addresses
  has_many :carts, dependent: :destroy
  rolify
  paginates_per 10
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :registerable,
         :recoverable, :rememberable, :validatable, :two_factor_authenticatable

         role = %w{admin guest}


         def admin?
           role == 'admin'
         end
         def guest?
           role == 'guest'
         end

         def run
          User.find_each do |user|
            UserMailer.with(user: user).deliver_later
          end
        end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)

    redirect_to edit_registration_path(resource_name) and return if should_disable_otp? && !disable_otp!

    process_standard_update
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:otp_attempt])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def should_disable_otp?
    resource.otp_required_for_login && params[:user][:otp_attempt].present? && params[:user][:current_password].present?
  end

  def disable_otp!
    otp_attempt = params[:user][:otp_attempt]
    current_password = params[:user][:current_password]

    if resource.validate_and_consume_otp!(otp_attempt) && resource.valid_password?(current_password)
      resource.otp_required_for_login = false
      resource.save!
      set_flash_message!(:notice, :otp_disabled)
      true
    else
      set_flash_message!(:alert, appropriate_error_message(otp_attempt, current_password))
      false
    end
  end

  def appropriate_error_message(otp_attempt, current_password)
    return :invalid_otp unless resource.validate_and_consume_otp!(otp_attempt)
    return :invalid_password unless resource.valid_password?(current_password)

    :invalid_otp_and_password
  end

  def process_standard_update
    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)
    resource_updated = update_resource(resource, account_update_params)
    yield resource if block_given?

    if resource_updated
      set_flash_message_for_update(resource, prev_unconfirmed_email)
      bypass_sign_in resource, scope: resource_name if sign_in_after_change_password?
      respond_with resource, location: after_update_path_for(resource)
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  #  before_action :configure_sign_in_params

  # GET /resource/sign_in
   def new
    super do |resource|
      if resource.persisted?
        if resource.verified == true
          sign_in(resource)
        end
        return
      end
    end
  end

  # POST /resource/sign_in
  def create
    # Authenticate user with just email and password.
    self.resource = warden.authenticate!(auth_options.merge(strategy: :password_authenticatable))

    if resource && resource.active_for_authentication?
      # If the user has 2FA enabled
      if resource.otp_required_for_login
        # Store the user ID temporarily. We're not saving the password in the session for security reasons.
        # Generate a signed token for the user ID.
        verifier = Rails.application.message_verifier(:otp_session)
        token = verifier.generate(resource.id)
        session[:otp_token] = token

        # Logout the user to wait for the 2FA verification
        sign_out(resource_name)

        # Redirect the user to the OTP entry page
        redirect_to user_otp_path and return
      else
        # If 2FA is not required, log the user in
        set_flash_message!(:notice, :signed_in)
        sign_in(resource_name, resource)
        yield resource if block_given?
        respond_with resource, location: after_sign_in_path_for(resource) and return
      end
    end

    # If user authentication failed
    flash[:alert] = 'Invalid email or password.'
    redirect_to new_user_session_path
  end


  def verify
    if @user.verified == true
      sign_in(@user)
    end
    return
    @user = User.find_by(verification_code: params[:verification_code])
    if @user
      if @user && @user.verification_code == params[:verification_code]

      end
    else
      redirect_to new_user_session_path, alert: 'Invalid verification code.'
    end
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:otp_attempt])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: %i[show_otp verify_otp]
  def index
    @users = User.all
   
  end

  def new 
    @user = User.new
  end

  def create
    authorize @user
    super do |user|
      user.role = 'guest' 
      user.save
    end
    @user = User.new(user_params)
    if @user.save!
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.first
    @user.destroy
    redirect_to root_path
  end

  def user
    if user_signed_in? && current_user.admin?
      @users = User.all
      @users = User.all.page params[:page]
    else
      redirect_to root_path, alert: "You have not access this page."
    end
  end

  def userinfo
   @users = User.all
  end

  def disable_otp
    if current_user.validate_and_consume_otp!(params[:otp_attempt])
      current_user.otp_required_for_login = false
      current_user.save!
      redirect_to root_path, notice: 'Two-factor authentication disabled successfully.'
    else
      flash[:alert] = 'Invalid OTP code.'
      redirect_back(fallback_location: root_path)
    end
  end

  def show_otp
    # Render the OTP entry page
  end

  def verify_otp
    verifier = Rails.application.message_verifier(:otp_session)
    user_id = verifier.verify(session[:otp_token])
    user = User.find(user_id)

    if user.validate_and_consume_otp!(params[:otp_attempt])
      sign_in(:user, user)
      redirect_to root_path, notice: 'Logged in successfully!'
    else
      flash[:alert] = 'Invalid OTP code.'
      redirect_to new_user_session_path
    end
  end

  def enable_otp_show_qr
    if current_user.otp_required_for_login
      redirect_to edit_user_registration_path, alert: '2FA is already enabled.'
    else
      current_user.otp_secret = User.generate_otp_secret
      issuer = 'Your App'
      label = "#{issuer}:#{current_user.email}"

      @provisioning_uri = current_user.otp_provisioning_uri(label, issuer:)
      current_user.save!
    end
  end

  def enable_otp_verify
    if current_user.validate_and_consume_otp!(params[:otp_attempt])
      current_user.otp_required_for_login = true
      current_user.save!
      redirect_to edit_user_registration_path, notice: '2FA enabled successfully.'
    else
      redirect_to enable_otp_show_qr_path, alert: 'Invalid OTP code.'
    end
  end
  private

  def user_params
    params.require(:user).permit(:email, :role)
  end

  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: @user, remote: true) do |f| %>
    <!-- Form fields go here -->
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

app/views/users/edit.html.erb
<h2>Edit Details</h2>

<%= form_with(model: @product, local: true) do |form| %>

  <div class="field">
    <%= form.label :email %><br />
    <%= form.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  
  <div class="actions">
    <%= form.submit "Update" %>
  </div>
<% end %>

app/views/users/enable_otp_show_qr.html.erb
<h2>Scan the QR Code to Enable Two Factor Authentication</h2>
<div>
  <%= raw RQRCode::QRCode.new(current_user.otp_provisioning_uri(current_user.email, issuer: "Devise-Two-Factor-Demo"),
                              :svg,
                              :level => :l,
                              :unit => 2).as_svg %>
</div>
<%= form_tag(enable_otp_verify_path, method: :post) do %>
  <div>
    <label for="otp_attempt">Enter OTP</label>
    <%= text_field_tag :otp_attempt %>
  </div>
  <%= submit_tag "Verify and Enable" %>
<% end %>
<%= link_to "Back", edit_user_registration_path %>

app/views/users/index.html.erb
<% if user_signed_in? %> 
 <div> Welcome <%= current_user.email %> </div> 
  <%= button_to "Sign out", destroy_user_session_path, method: :delete %> 
<% else %>
  <%= link_to "Sign in", new_user_session_path %>&nbsp &nbsp &nbsp
  <%= link_to "sign_up", new_user_registration_path %>
<% end %>
<br>

app/views/users/show.html.erb
<h1> User Details </h1>

<strong><%= @user.email %></strong>

app/views/users/show_otp.html.erb
<style>
.background-img {
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-image: url('https://www.shutterstock.com/image-photo/compliance-rules-law-regulation-policy-600nw-1171280545.jpg');
  background-size: cover;
  z-index: -1; 
}
</style>
<div class="background-img">
  <div class="mt-5 d-flex justify-content-around align-items-center">
    <div class="container">
      <div class="row">
        <div class="col-sm-9 col-md-7 col-lg mx-auto">
          <div class="card my-5 shadow">
            <div class="card-body">
              <div class="row">
              <div class="d-flex justify-content-center">
              <%= form_tag verify_user_otp_path, method: :post do %>
                <div class="field">
                  <div class="d-flex justify-content-center">
                  <%= label_tag :otp_attempt, "OTP Code" %><br />
                  </div>
                  <%= text_field_tag :otp_attempt do %>
                    <div id="inputs" class="inputs"><input class="input" type="text" inputmode="numeric" maxlength="1" autofocus="true"><input class="input" type="text" inputmode="numeric" maxlength="1"><input class="input" type="text" inputmode="numeric" maxlength="1"><input class="input" type="text" inputmode="numeric" maxlength="1"><input class="input" type="text" inputmode="numeric" maxlength="1"><input class="input" type="text" inputmode="numeric" maxlength="1"></div>
                <% end %>
                    </div>
                <br>
                <div class="d-flex justify-content-center">
                <div class="actions">
                  <%= submit_tag "Verify", class:"btn btn-secondary btn-lg" %>
                </div>
                </div>
              <% end %>  
                    </div>
                    </div>
                    </div>
                  </div>
                </div>
              </div>
            </div> 
  </div>
</div>

<script>
const inputs = document.getElementById("inputs");

inputs.addEventListener("input", function (e) {
  const target = e.target;
  const val = target.value;

  if (isNaN(val)) {
    target.value = "";
    return;
  }

  if (val != "") {
    const next = target.nextElementSibling;
    if (next) {
      next.focus();
    }
  }
});

inputs.addEventListener("keyup", function (e) {
  const target = e.target;
  const key = e.key.toLowerCase();

  if (key == "backspace" || key == "delete") {
    target.value = "";
    const prev = target.previousElementSibling;
    if (prev) {
      prev.focus();
    }
    return;
  }
});
</script>

<style>
.container {
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 100vh;
}

.input {
  width: 40px;
  border: none;
  border-bottom: 3px solid rgba(0, 0, 0, 0.5);
  margin: 0 10px;
  text-align: center;
  font-size: 36px;
  cursor: not-allowed;
  pointer-events: none;
}

.input:focus {
  border-bottom: 3px solid orange;
  outline: none;
}

.input:nth-child(1) {
  cursor: pointer;
  pointer-events: all;
}
</style>

app/views/users/user.html.erb
<% if user_signed_in? %> 
 <div> Welcome <b><%= current_user.role %></b> </div> 
  <%= button_to "Sign out", destroy_user_session_path, method: :delete %> 
<% else %>
  <%= link_to "Sign in", new_user_session_path %>&nbsp &nbsp &nbsp
  <%= link_to "sign_up", new_user_registration_path %>
<% end %>
<br>

<table class="table table-bordered text-center">

  <tr>
    <th>User Email</th>
    <th> User Role</th>
    <th colspan=2> Action </th>
  </tr>
  <% @users.each do |user| %> 
  <tr>
  <%= link_to user_path(user), style:"text-decoration: none;" do %>
    <td><%= user.email %></td>
    <% end %>
    <td><%= user.role %></td>
    <td> <%= link_to "Edit", edit_user_registration_path(user), class:"btn btn-primary" %></td> 
    <td> <%= button_to "Delete", user_path(user), method: :delete, class:"btn btn-danger" %></td> 
  </tr>
  <% end %>
</table>

<div class="pagination justify-content-center">
 <%= paginate @users %>
</div>

app/views/users/userinfo.html.erb
<h1> User Information </h1>

<strong> <%= current_user.email %> </strong><br>
<br>
<% if current_user.admin? %>
   <br> <%= button_to "Sign out", destroy_user_session_path, method: :delete, class:"btn btn-primary" %>
<% else %>
<%= link_to "Edit", edit_user_path(current_user), class:"btn btn-primary" %><br> 
<br> <%= button_to "Sign out", destroy_user_session_path, method: :delete, class:"btn btn-primary" %>
<% end %>