config/routes.rb
Rails.application.routes.draw do
  get 'categories/new'
  get 'categories/create'
  resources :products do
    post '/update_quantity', to: 'products#update_quantity'
    collection do
      get '/products', to: 'products#product', as: 'products'
      get 'products/products', to: 'products#next_batch', as: 'products_products'

    end
    resources :similar_products
    collection do
      get 'filtered'
    end
  end 
  resources :carts do
    resources :lineitems
  end
  resources :carts do
    post 'add_to_cart', on: :collection
  delete 'remove_item', on: :member
  end
  resources :lineitems do
    patch 'increase_quantity', on: :member
    patch 'decrease_quantity', on: :member
    patch 'increase_stk', on: :member
    patch 'decrease_stk', on: :member
  end
  resources :categories 


  resources :orders do
    get '/status', to: 'orders#status', as: 'status'
  end
  resources :addresses

  devise_for :users, controllers: { registrations: 'users/registrations',
    sessions: 'users/sessions'}
  devise_scope :user do
    get '/verify_user', to: 'devise/sessions#verify'
  end

  get 'enable_otp_show_qr', to: 'users#enable_otp_show_qr', as: 'enable_otp_show_qr'
  post 'enable_otp_verify', to: 'users#enable_otp_verify', as: 'enable_otp_verify'

  get 'users/otp', to: 'users#show_otp', as: 'user_otp'
  post 'users/otp', to: 'users#verify_otp', as: 'verify_user_otp'
  post 'verify_otp', to: 'users/sessions#verify_otp'
  
  root to: "products#index"
  resources :payments, only: [:create, :show, :new] do
    collection do
      post '/create_payment', to: 'payments#create_payment'
      post 'payment_callback'
      get '/success', to: 'payments#success', as: 'success'
      get '/offline_payment', to: 'payments#offline_payment', as: 'offline_payment'
      get '/invoice_print', to: 'payments#invoice_print', as: 'invoice_print'
      get 'download_pdf'
      post '/update_status', to: 'payments#update_status'
    end
  end
  post '/payments/create_payment/:order_id', to: 'payments#create_payment', as: 'create_payment'
  resources :razorpay, only: [:create_payment, :payment_callback]
  resources :users do
     collection do
       get 'user'
       get 'userinfo'
     end
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :lineitems, dependent: :destroy
    has_many :orders
    
    
    def add_product(product, quantity, size_ids)
        size_ids = Array(size_ids)
        size_ids.each do |size_id|
          current_item = lineitems.find_or_initialize_by(product_id: product.id)
            lineitem_size = current_item.lineitem_sizes.find_or_initialize_by(size_id: size_id)
            lineitem_size.update(quantity: quantity)
          if current_item.persisted?
            qty = current_item.quantity.to_i > 0 ? current_item.quantity.to_i + quantity.to_i : quantity.to_i
            current_item.update(quantity: qty)
            
            stk = lineitem_size.quantity.to_i > 0 ? lineitem_size.quantity.to_i + quantity.to_i : quantity.to_i
            lineitem_size.update(quantity: stk)
          else
            current_item = lineitems.build(product_id: product.id, size_id: size_ids, quantity: quantity)
          end
          current_item
        end
    end

    def unit_price
        lineitems.to_a.sum {|item| item.unit_price }
    end

    def subtotal
        lineitems.to_a.sum(&:unit_price)
    end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    include CurrentCart
    rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
    before_action :set_cart, only: [:show, :edit, :update, :destroy]

    def index
      @carts = Cart.all
      add_breadcrumb "index", index_path
    end

    def show
      @subtotal = @cart.lineitems.sum(&:unit_price)
      @cart.update(subtotal: @cart.subtotal)
      
      add_breadcrumb('<div style="text-align: center;"><img src="https://cdn-icons-png.flaticon.com/128/10595/10595791.png" style="width: 20px; height: 20px;"><br>Cart</div>'.html_safe, cart_path(@cart), class: 'breadcrumb-item', data: { index: 1 })
      add_breadcrumb('<div style="text-align: center;"><img src="https://cdn-icons-png.flaticon.com/128/10595/10595792.png" style="width: 20px; height: 20px;"><br>Order</div>'.html_safe, orders_path, class: 'breadcrumb-item',style:"color:blue;", data: { index: 2 })
      add_breadcrumb('<div style="text-align: center;"><img src="https://cdn-icons-png.flaticon.com/128/10595/10595793.png" style="width: 20px; height: 20px;"><br>Address</div>'.html_safe, new_address_path(cart_id: @cart.id), class: 'breadcrumb-item',style:"color:blue;", data: { index: 3 })
      add_breadcrumb('<div style="text-align: center;"><img src="https://cdn-icons-png.flaticon.com/128/10595/10595794.png" style="width: 20px; height: 20px;"><br>Payment</div>'.html_safe, new_payment_path(cart_id: @cart.id), class: 'breadcrumb-item',style:"color:blue;", data: { index: 4 })

    end

    def new
        @cart = Cart.new
    end

    def create
        @cart = Cart.new(cart_params)

    end

    def destroy
        @cart.destroy if @cart.id == session[:cart_id]
        session[:cart_id] = nil
        respond_to do |format|
            format.html { redirect_to root_path, notice: 'Cart Was Succesfully Destroyed.'}
            format.json { head :no_content }
        end
    end

    def edit
        @cart = Cart.find(params[:id])
    end

    def update
        @cart = Cart.find(params[:id])

        if @cart.update(cart_params)
          redirect_to @cart
        else
          render :edit, status: :unprocessable_entity
        end
    end
    

      def remove_item
        lineitem = Lineitem.find(params[:id])
        lineitem.destroy
        redirect_to cart_path(lineitem.cart)
      end

    private

    def set_cart
        @cart = Cart.find(params[:id])
    end

    def cart_params
        params.fetch(:cart, {})
    end

    def invalid_cart
        logger.error "Attempt to access invalid cart#{params[:id]}"
        redirect_to root_path, notice: "That cart doesn't exists"
    end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/carts/_lineitem.html.erb
<html>
<body>
<strong>Quantity:</strong> &nbsp <%= lineitem.quantity %><br>
        <%= link_to "Add Quantity", increase_quantity_lineitem_path(lineitem), method: :patch, class:"btn btn-outline-success increase-quantity",remote: true%>

        <%= link_to "Remove Quantity", decrease_quantity_lineitem_path(lineitem), method: :patch, class:"btn btn-outline-success decrease-quantity"%>

        <script>
        $(document).ready(function() {
          $('.increase-quantity').click(function(event) {
            event.preventDefault();
            var lineitemId = $(this).data('lineitemId');
            console.log("wwwwwwwwwwwww");

            $.ajax({
               url: '/lineitems/increase_quantity',
               method: 'PATCH', 
               data: { id: lineitemId },
              success: function(response) {
                console.log('Quantity increased successfully');
        },
              error: function(xhr, status, error) {
              console.error('Error increasing quantity:', error);
        }
      });
          });
  
          $('.decrease-quantity').click(function(event) {
            event.preventDefault();
            var lineitemId = $(this).data('lineitemId');
            $.ajax({
              url: '/lineitems/decrease_quantity',
              method: 'PATCH', 
              data:{ id: lineitemId },
              success: function(response) {
          
              console.log('Quantity decreased successfully');
    
        },
            error: function(xhr, status, error) {
            console.error('Error decreasing quantity:', error);
        }
      });
  
          });
        });
      </script>
</body>
</html>

app/views/carts/show.html.erb
<html>
<body>
<h2> Your Cart </h2>
<%= form_with(model: Order.new, url: orders_path, method: :get) do |form| %>
  <%= hidden_field_tag :cart_id, @cart.id %>
  <%= hidden_field_tag :user_id, current_user.id %>
<div class="d-flex justify-content-end">       
   <%= link_to 'Continue Shopping', products_path, class:"btn btn-outline-success btn-lg" %>&nbsp &nbsp
   <%= form.submit 'Place Order', class:"btn btn-outline-success btn-lg"%>
</div>
<hr/>
<div class="d-flex justify-content-end subtotal">
  <h4><strong>Cart Subtotal: </strong><%= number_to_currency(@subtotal, unit: "₹", format: "%u %n") %></h4>
</div>
<% @cart.lineitems.each do |lineitem| %>

<div class="container mt-5">
    <div class="row">
      <div class="col-md-3">
         <%= image_tag lineitem.product.images.first, size:"210x210"%><br>
      </div>
      <div class="col-md-6">
        <div style="font-size:21px;">
          <h2><%= lineitem.product.name %></h2>
          <strong>Product Description:</strong> &nbsp <%= lineitem.product.desc %><br>
          <strong> Sizes:</strong>&nbsp
          <div class="size-buttons">
          <% lineitem.sizes.each do |size| %> 
            <button class="size-button submit-button" type="button" id="size_<%= size.id %> activateButton" data-size-id="<%= size.id %>">
            <%= size.abbreviation %><br>
          <% end %>
          </button>
          </div>
          <div class="qty">
          <strong>Quantity: </strong> &nbsp 
            <%= lineitem.lineitem_sizes.pluck(:quantity).join(',') %>
          </div>
          <div class="d-flex grid gap-4">
          <%= link_to increase_stk_lineitem_path(lineitem), method: :patch,remote: true,class:"increase-stk "  do %>
            <%= image_tag "https://cdn-icons-png.flaticon.com/128/9293/9293648.png",size:"35x35", alt: "Logo" %>
          <% end %>
          <%= link_to decrease_stk_lineitem_path(lineitem), method: :patch,remote: true, class:"decrease-stk " do %>
            <%= image_tag "https://cdn-icons-png.flaticon.com/128/54/54373.png",size:"31x31"%>
          <% end %>
          </div>
          <div class="price_<%= lineitem.id %>"> <strong>Price:</strong> &nbsp  <%= number_to_currency(lineitem.unit_price, unit: "₹", format: "%u %n") %></div>
          
        </div>
      </div>   
      <div class="col-md-3 mt-2 d-flex justify-content-around align-items-center">
        <%= link_to increase_quantity_lineitem_path(lineitem), method: :patch,remote: true, class:"increase-quantity"  do %>
          <%= image_tag "https://cdn-icons-png.flaticon.com/128/3032/3032220.png",size:"35x35", alt: "Logo" %>
        <% end %>

        <%= link_to decrease_quantity_lineitem_path(lineitem), method: :patch,remote: true, class:"decrease-quantity" do %>
          <%= image_tag "https://cdn-icons-png.flaticon.com/128/2740/2740653.png",size:"42x42"%>
        <% end %>

        <%= link_to remove_item_cart_path(lineitem), method: :delete, data: { confirm: "Are you sure?" },remote: true  do %>
          <%= image_tag "https://cdn-icons-png.flaticon.com/128/1/1570.png",size:"35x35", alt: "Logo" %>
        <% end %>
      </div>
      </div>
      <br>
      <hr>
</div>
<% end %>
<% end %>
</body>
</html>

         <script>
            $(document).ready(function() {
              $('.increase-quantity').click(function(event) {
                event.preventDefault();
                $.ajax({
                    url: '/lineitems/increase_quantity',
                   method: 'PATCH', 
                   dataType: 'script',
                  success: function(response) {
                    console.log('Quantity increased successfully');
                   }
                });
              });
              $('.increase-stk').click(function(event) {
                event.preventDefault();
                var sizeId = $('.size-button').data('size-id');
                var lineitem_id = $(this).data('lineitem_id');
                if(sizeId){
                $.ajax({
                    url: '/lineitems/increase_stk',
                   method: 'PATCH', 
                   dataType: 'script',
                   data: { size_id: sizeId,
                   id: lineitem_id },
                  success: function(response) {
                    console.log(' Stock Quantity increased successfully');
                    console.log(sizeId);
                   }
                });
              }
            else{
              console.error('size_id is missing or invalid');
            }
              });
              $('.decrease-stk').click(function(event) {
                event.preventDefault();
                var sizeId = $('.size-button').data('size-id');
                var lineitem_id = $(this).data('lineitem_id');
                if(sizeId){
                $.ajax({
                    url: '/lineitems/decrease_stk',
                   method: 'PATCH', 
                   dataType: 'script',
                   data: { size_id: sizeId,
                  id: lineitem_id },
                  success: function(response) {
                    console.log(' Stock Quantity decreased successfully');
                   }
                });
                  }
              else{
                console.error('size_id is missing or invalid');
              }
              });
              $('.decrease-quantity').click(function(event) {
                event.preventDefault();
                var lineitem_id = $(this).data('lineitem_id');
                $.ajax({
                  url:'/lineitems/decrease_quantity',
                  method: 'PATCH', 
                  dataType: 'script',
                  data:{ id: lineitem_id },
                  success: function(response) {
                  console.log('Quantity decreased successfully');
                  }
          });
      
              });
              
            });
          </script>

          