config/routes.rb
Rails.application.routes.draw do
  get 'categories/new'
  get 'categories/create'
  resources :products do
    post '/update_quantity', to: 'products#update_quantity'
    collection do
      get '/products', to: 'products#product', as: 'products'
      get 'products/products', to: 'products#next_batch', as: 'products_products'

    end
    resources :similar_products
    collection do
      get 'filtered'
    end
  end 
  resources :carts do
    resources :lineitems
  end
  resources :carts do
    post 'add_to_cart', on: :collection
  delete 'remove_item', on: :member
  end
  resources :lineitems do
    patch 'increase_quantity', on: :member
    patch 'decrease_quantity', on: :member
    patch 'increase_stk', on: :member
    patch 'decrease_stk', on: :member
  end
  resources :categories 


  resources :orders do
    get '/status', to: 'orders#status', as: 'status'
  end
  resources :addresses

  devise_for :users, controllers: { registrations: 'users/registrations',
    sessions: 'users/sessions'}
  devise_scope :user do
    get '/verify_user', to: 'devise/sessions#verify'
  end

  get 'enable_otp_show_qr', to: 'users#enable_otp_show_qr', as: 'enable_otp_show_qr'
  post 'enable_otp_verify', to: 'users#enable_otp_verify', as: 'enable_otp_verify'

  get 'users/otp', to: 'users#show_otp', as: 'user_otp'
  post 'users/otp', to: 'users#verify_otp', as: 'verify_user_otp'
  post 'verify_otp', to: 'users/sessions#verify_otp'
  
  root to: "products#index"
  resources :payments, only: [:create, :show, :new] do
    collection do
      post '/create_payment', to: 'payments#create_payment'
      post 'payment_callback'
      get '/success', to: 'payments#success', as: 'success'
      get '/offline_payment', to: 'payments#offline_payment', as: 'offline_payment'
      get '/invoice_print', to: 'payments#invoice_print', as: 'invoice_print'
      get 'download_pdf'
      post '/update_status', to: 'payments#update_status'
    end
  end
  post '/payments/create_payment/:order_id', to: 'payments#create_payment', as: 'create_payment'
  resources :razorpay, only: [:create_payment, :payment_callback]
  resources :users do
     collection do
       get 'user'
       get 'userinfo'
     end
  end
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :user
   
    validates :pincode, numericality: { only_integer: true}, length: { is: 6 }
    validates :name, presence: true
    validates :phone_no, numericality: { only_integer: true}, length: { is: 10 }
    validates :address, presence: true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :lineitems, dependent: :destroy
    has_many :orders
    
    
    def add_product(product, quantity, size_ids)
        size_ids = Array(size_ids)
        size_ids.each do |size_id|
          current_item = lineitems.find_or_initialize_by(product_id: product.id)
            lineitem_size = current_item.lineitem_sizes.find_or_initialize_by(size_id: size_id)
            lineitem_size.update(quantity: quantity)
          if current_item.persisted?
            qty = current_item.quantity.to_i > 0 ? current_item.quantity.to_i + quantity.to_i : quantity.to_i
            current_item.update(quantity: qty)
            
            stk = lineitem_size.quantity.to_i > 0 ? lineitem_size.quantity.to_i + quantity.to_i : quantity.to_i
            lineitem_size.update(quantity: stk)
          else
            current_item = lineitems.build(product_id: product.id, size_id: size_ids, quantity: quantity)
          end
          current_item
        end
    end

    def unit_price
        lineitems.to_a.sum {|item| item.unit_price }
    end

    def subtotal
        lineitems.to_a.sum(&:unit_price)
    end

end

app/models/category.rb
class Category < ApplicationRecord
    has_and_belongs_to_many :products
    has_many_attached :images

end

app/models/lineitem.rb
class Lineitem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
  has_many :lineitem_sizes
  has_many :sizes, through: :lineitem_sizes


  def unit_price
    product.price.to_i * quantity.to_i
  end

  def total_quantity
    product.quantity.to_i - quantity.to_i
  end
  
end

app/models/lineitem_size.rb
class LineitemSize < ApplicationRecord
  belongs_to :lineitem
  belongs_to :size
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    belongs_to :cart
    has_one :payment

  validates :user_id, presence: true
  validates :cart_id, presence: true

  enum track: { OrderPlaced: 0, Shipped: 1, Delivered: 2, Received: 3 }
  
end

app/models/payment.rb
class Payment < ApplicationRecord
    belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
    before_destroy :not_referenced_by_any_lineitem  
    has_many :sizes
    has_many :lineitems
    has_many_attached :images
    has_many :similar_products
    has_and_belongs_to_many :categories
    

    validates :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 0 }


    def not_referenced_by_any_lineitem
        unless lineitems.empty?
            error.add(:base, "Line items present")
            throw :abort
        end
    end

    def self.ransackable_attributes(_auth_object)
        ["name"]
      end
  
      def self.ransackable_associations(auth_object = nil)
        []
      end 
  

    

end

app/models/product_size.rb
class ProductSize < ApplicationRecord
  belongs_to :product
  belongs_to :size
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/similar_product.rb
class SimilarProduct < ApplicationRecord
    belongs_to :product
    has_many_attached :images

end

app/models/size.rb
class Size < ApplicationRecord
  belongs_to :product
  has_many :lineitem_sizes
  has_many :lineitems, through: :lineitem_sizes
end

app/models/user.rb
class User < ApplicationRecord
  devise :two_factor_authenticatable
  has_many :orders
  has_many :addresses
  has_many :carts, dependent: :destroy
  rolify
  paginates_per 10
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :registerable,
         :recoverable, :rememberable, :validatable, :two_factor_authenticatable

         role = %w{admin guest}


         def admin?
           role == 'admin'
         end
         def guest?
           role == 'guest'
         end

         def run
          User.find_each do |user|
            UserMailer.with(user: user).deliver_later
          end
        end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    @categories = Category.all 
    @products = Product.all
  end

  def new
    @category = Category.new
  end


  def show
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to root_path, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end
  
  private

  def category_params
    params.require(:category).permit(:name, :desc, :product_id, images: [])
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/lineitem_helper.rb
module LineitemHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sizes_helper.rb
module SizesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: @category, local: true) do |form| %>
    <% if @category.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
  
        <ul>
          <% @category.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="background">
    <section class="vh-100">
      <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col-12 col-md-8 col-lg-6 col-xl-5">
            <div class="card shadow-2-strong" style="border-radius: 1rem;">
              <div class="card-body p-5 text-center">

                <h3 class="mb-5">Add Category</h3>

                <div class="form-outline mb-4">
                  
                <%= form.label :name %>
                <%= form.text_field :name, autofocus: true, autocomplete: "name",class:"form-control form-control-lg" %>
                </div>

                <div class="form-outline mb-4">
                <%= form.label :desc %>
                <%= form.text_field :desc ,class:"form-control form-control-lg" %>
                </div>

                <div class="form-outline mb-4">
                <%= form.label :images %>
                <%= form.file_field :images, multiple: true %>
                </div>

                <div class="action mb-4">
                <%= form.submit class:"btn btn-primary btn-lg" %>
                </div>
               
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
</div>
  <% end %>

app/views/categories/edit.html.erb
<h1> Edit Details </h1>
<%= render "form", category: @category %>

app/views/categories/index.html.erb
<div class="row row-cols-1 row-cols-md-3 g-4 mt-4  justify-content-center">
    <% @categories.each do |category|%>
        <div class="card m-1" style="width: 25rem; height: 34rem;">
        <%= link_to products_path(category_id: category.id), style:"text-decoration: none;" do %>
        <% if category.images.attached? %>
          <%= image_tag category.images.first, class:"card-img-top", size:"350x350"%>
        <% end %>
        <div class="card-body">
        <h5 class="card-title text-dark"><%= category.name %></h5>
        <h5 class="card-title text-dark"><%= category.desc %></h5>
        <%= link_to "Show Products", category_path(category), class:"btn btn-outline-success justify-content-center d-flex"%>
        <% end %>
        </div>
    </div>
    <% end %>
    </div>

app/views/categories/new.html.erb
<%= render "form", category: @category %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<% if @category.products.present? %>
<div class="row row-cols-1 row-cols-md-3 g-4 mt-4 justify-content-center">
    <% @category.products.each do |product| %>
      <div class="card m-1" style="width: 25rem; height: 45rem;">
        <%= link_to product_path(product), style: "text-decoration: none;" do %>
          <% if product.images.attached? %>
            <%= image_tag product.images.first, class: "card-img-top", size: "400x500" %>
          <% end %>
          <div class="card-body">
            <h5 class="card-title text-dark"><%= product.name %></h5>
            <div class="text-dark">
              <strong>Price:</strong> &nbsp <%= number_to_currency(product.price, unit: "₹", format: "%u %n") %><br><br>
            </div>
            <%= link_to "Show Product", product_path(product), class: "btn btn-outline-success justify-content-center d-flex" %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
<% else %>
<div class="card m-1" style="width: 25rem; height: 45rem;">
<% if @category.images.attached? %>
  <%= image_tag @category.images.first, class: "card-img-top", size: "400x500" %>
<% end %>
<div class="card-body">
  <h5 class="card-title text-dark"><%= @category.desc %></h5>
</div>
</div>
</div>
<% end %>