config/routes.rb
Rails.application.routes.draw do
  get 'categories/new'
  get 'categories/create'
  resources :products do
    post '/update_quantity', to: 'products#update_quantity'
    collection do
      get '/products', to: 'products#product', as: 'products'
      get 'products/products', to: 'products#next_batch', as: 'products_products'

    end
    resources :similar_products
    collection do
      get 'filtered'
    end
  end 
  resources :carts do
    resources :lineitems
  end
  resources :carts do
    post 'add_to_cart', on: :collection
  delete 'remove_item', on: :member
  end
  resources :lineitems do
    patch 'increase_quantity', on: :member
    patch 'decrease_quantity', on: :member
    patch 'increase_stk', on: :member
    patch 'decrease_stk', on: :member
  end
  resources :categories 


  resources :orders do
    get '/status', to: 'orders#status', as: 'status'
  end
  resources :addresses

  devise_for :users, controllers: { registrations: 'users/registrations',
    sessions: 'users/sessions'}
  devise_scope :user do
    get '/verify_user', to: 'devise/sessions#verify'
  end

  get 'enable_otp_show_qr', to: 'users#enable_otp_show_qr', as: 'enable_otp_show_qr'
  post 'enable_otp_verify', to: 'users#enable_otp_verify', as: 'enable_otp_verify'

  get 'users/otp', to: 'users#show_otp', as: 'user_otp'
  post 'users/otp', to: 'users#verify_otp', as: 'verify_user_otp'
  post 'verify_otp', to: 'users/sessions#verify_otp'
  
  root to: "products#index"
  resources :payments, only: [:create, :show, :new] do
    collection do
      post '/create_payment', to: 'payments#create_payment'
      post 'payment_callback'
      get '/success', to: 'payments#success', as: 'success'
      get '/offline_payment', to: 'payments#offline_payment', as: 'offline_payment'
      get '/invoice_print', to: 'payments#invoice_print', as: 'invoice_print'
      get 'download_pdf'
      post '/update_status', to: 'payments#update_status'
    end
  end
  post '/payments/create_payment/:order_id', to: 'payments#create_payment', as: 'create_payment'
  resources :razorpay, only: [:create_payment, :payment_callback]
  resources :users do
     collection do
       get 'user'
       get 'userinfo'
     end
  end
end

app/models/product.rb
class Product < ApplicationRecord
    before_destroy :not_referenced_by_any_lineitem  
    has_many :sizes
    has_many :lineitems
    has_many_attached :images
    has_many :similar_products
    has_and_belongs_to_many :categories
    

    validates :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 0 }


    def not_referenced_by_any_lineitem
        unless lineitems.empty?
            error.add(:base, "Line items present")
            throw :abort
        end
    end

    def self.ransackable_attributes(_auth_object)
        ["name"]
      end
  
      def self.ransackable_associations(auth_object = nil)
        []
      end 
  

    

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @products = Product.all
    @categories = Category.all
    @products = @category ? @category.products : Product.all
  end

  def show
    @product = Product.find(params[:id])
    @sizes = @product.sizes
    @products = Product.all
    @total_quantity = @product.quantity
    @similar_products = @product.similar_products
    @size = Size.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new

  end

  def create
    @product = Product.new(product_params)
    @product.category_ids = params[:product][:category_id]
    if @product.save
        redirect_to @product
    else
        render :new, status: :unprocessable_entity
    end
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to @product
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product = Product.find( params[:id])
    @product.destroy
    redirect_to root_path
  end

  def add_to_cart
    @product = Product.find(params[:id])
    quantity = params[:quantity].to_i
    current_cart.add_item(@product, quantity)
    redirect_to cart_path(current_cart), notice: "Added #{quantity} #{'item'.pluralize(quantity)} to cart."
  end

  def filtered
    @category = Category.find_by(name: params[:category])
    if @category
      @products = @category.products
    else
      redirect_to products_path, alert: "Category not found"
    end
  end

  def product
    @category = Category.find_by(id: params[:category])
    if @category
      @products = @category.products if @category.present?
    else
      @products = Product.all
    end
  end

  def next_batch
    @products = Product.page(params[:page]).per(10) # Adjust per() according to your desired number of products per page

    # Render the next batch of products without layout to be used in AJAX request
    render partial: 'product_batch', locals: { products: @products }
  end
  private

  def product_params
    params.require(:product).permit(:name, :desc, :price, :size, :quantity, :id, images: [])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: @product, local: true) do |form| %>
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    
    <div class="field">
    <%= form.label :desc %>
    <%= form.text_field :desc %>
    </div>

    <div class="field">
      <%= form.label :price %>
      <%= form.number_field :price %>
    </div>
    <div class="field">
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true %>
    </div>
    
   

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, min: 0 %>
  </div>

    <div class="actions">
      <%= form.submit %>
     
    </div>
  <% end %>

app/views/products/_product_batch.html.erb
<% products.each do |product| %>
    <div class="card m-1" style="width: 20rem;">
      <%= link_to product_path(product), style: "text-decoration: none;" do %>
        <% if product.images.attached? %>
          <%= image_tag product.images.first, class: "card-img-top", size: "400x400" %>
        <% end %>
        <div class="card-body">
          <h5 class="card-title text-dark"><%= product.name %></h5>
          <div class="text-dark">
            <strong>Price:</strong> <%= number_to_currency(product.price, unit: "₹", format: "%u %n") %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>

app/views/products/_quantity.html.erb
<%= @product.quantity %>

app/views/products/_verify.html.erb
<style>
.background-img {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-image: url('https://www.shutterstock.com/image-photo/compliance-rules-law-regulation-policy-600nw-1171280545.jpg');
  background-size: cover;
  z-index: -1; 
}
</style>
<div class="background-img">
  <div class="mt-5 d-flex justify-content-around align-items-center">
    <div class="container">
      <div class="row">
        <div class="col-sm-9 col-md-7 col-lg mx-auto">
          <div class="card my-5 shadow">
            <div class="card-body">
              <div class="row">
              <div class="d-flex justify-content-center">
              <%= form_with url: products_products_path, method: :get do |f| %>
                <div class="field">
                <div class="d-flex justify-content-center">
                  <%= f.label :verification_code, "Verification Code" %>
                </div>
                  <div id="inputs" class="inputs" placeholder=<%= @verification_code %>"><input class="input" type="text" inputmode="numeric" maxlength="1" autofocus="true"><input class="input" type="text" inputmode="numeric" maxlength="1"><input class="input" type="text" inputmode="numeric" maxlength="1"><input class="input" type="text" inputmode="numeric" maxlength="1"><input class="input" type="text" inputmode="numeric" maxlength="1"><input class="input" type="text" inputmode="numeric" maxlength="1"><input class="input" type="text" inputmode="numeric" maxlength="1"></div>
                </div>
                <br>
                <div class="d-flex justify-content-center">
                <div class="actions">
                  <%= f.submit "Verify", class:"btn btn-secondary btn-lg" %>
                </div>
                </div>
              <% end %>  
                    </div>
                    </div>
                    </div>
                  </div>
                </div>
              </div>
            </div> 
  </div>
</div>

<script>
const inputs = document.getElementById("inputs");

inputs.addEventListener("input", function (e) {
  const target = e.target;
  const val = target.value;

  if (isNaN(val)) {
    target.value = "";
    return;
  }

  if (val != "") {
    const next = target.nextElementSibling;
    if (next) {
      next.focus();
    }
  }
});

inputs.addEventListener("keyup", function (e) {
  const target = e.target;
  const key = e.key.toLowerCase();

  if (key == "backspace" || key == "delete") {
    target.value = "";
    const prev = target.previousElementSibling;
    if (prev) {
      prev.focus();
    }
    return;
  }
});
</script>

<style>
.container {
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 100vh;
}

.input {
  width: 40px;
  border: none;
  border-bottom: 3px solid rgba(0, 0, 0, 0.5);
  margin: 0 10px;
  text-align: center;
  font-size: 36px;
  cursor: not-allowed;
  pointer-events: none;
}

.input:focus {
  border-bottom: 3px solid orange;
  outline: none;
}

.input:nth-child(1) {
  cursor: pointer;
  pointer-events: all;
}
</style>

app/views/products/edit.html.erb
<h1> Edit Details </h1>
<%= render "form", product: @product %>

app/views/products/filtered.html.erb
<% if @category.products.present? %>
  <div class="row row-cols-1 row-cols-md-3 g-4 mt-4 justify-content-center">
    <% @products.each do |product| %>
      <div class="card m-1" style="width: 25rem; height: 34rem;">
        <%= link_to product_path(product), style: "text-decoration: none;" do %>
          <% if product.images.attached? %>
            <%= image_tag product.images.first, class: "card-img-top", size: "350x350" %>
          <% end %>
          <div class="card-body">
            <h5 class="card-title text-dark"><%= product.name %></h5>
            <div class="text-dark">
              <strong>Price:</strong> &nbsp <%= number_to_currency(product.price, unit: "₹", format: "%u %n") %><br><br>
            </div>
            <%= link_to "Show Product", product_path(product), class: "btn btn-outline-success justify-content-center d-flex" %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
<% else %>
  <h1>No products found for category: <%= params[:category] %></h1>
<% end %>

app/views/products/index.html.erb
<% if user_signed_in? %>
     
<% else %>
  <%= render partial:"layouts/navbar" %>
<% end %>
<div class="d-flex justify-content-end">
  <% if current_user.present? && current_user.admin? %>
    <%= link_to new_product_path, style: "text-decoration: none;" do %>
      <%= image_tag "https://cdn-icons-png.flaticon.com/128/3032/3032220.png", size: "40x40", alt: "Logo" %>
    <% end %>
  <% end %>
</div>
<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel" data-bs-interval="1500">
  <div class="carousel-inner" style="height:60%;">
    <div class="carousel-item active">
      <img class="d-block w-100 h-70" src="https://images.unsplash.com/photo-1483181957632-8bda974cbc91?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" width="1900" height="590">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100 h-70" src="https://images.unsplash.com/photo-1601924994987-69e26d50dc26?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" width="1900" height="590">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100 h-70" src="https://images.unsplash.com/photo-1487744480471-9ca1bca6fb7d?q=80&w=2091&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" width="1900" height="590">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only"></span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only"></span>
  </a>
</div>
<br>
<ul class="nav justify-content-center">
<li class="nav-item dropdown">
<a class="nav-link dropdown-toggle text-dark" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Men's Wear</a>
<ul class="dropdown-menu">
  <li><a class="dropdown-item" href="categories/1">Top Wear</a></li>
  <li><a class="dropdown-item" href="categories/7">Bottom Wear</a></li>
  <li><a class="dropdown-item" href="categories/6">Party Wear</a></li>
  <li><a class="dropdown-item" href="categories/4">Summer Wear</a></li>
  <li><a class="dropdown-item" href="categories/5">Winter Wear</a></li>
  <li><a class="dropdown-item" href="categories/11">Foot Wear</a></li>
</ul>
</li>
<li class="nav-item dropdown">
<a class="nav-link dropdown-toggle text-dark" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Women's Wear</a>
<ul class="dropdown-menu">
<li><a class="dropdown-item" href="categories/2">Top Wear</a></li>
<li><a class="dropdown-item" href="categories/8">Bottom Wear</a></li>
<li><a class="dropdown-item" href="categories/6">Party Wear</a></li>
<li><a class="dropdown-item" href="categories/10">Ethnic Wear</a></li>
</ul>
</li>
<li class="nav-item dropdown">
<a class="nav-link dropdown-toggle text-dark" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Chidren's Waer</a>
<ul class="dropdown-menu">
<li><a class="dropdown-item" href="categories/3">Top Wear</a></li>
<li><a class="dropdown-item" href="categories/9">Bottom Wear</a></li>
<li><a class="dropdown-item" href="categories/6">Party Wear</a></li>
<li><a class="dropdown-item" href="categories/11">Foot Wear</a></li>
</ul>
</li>
</ul>

    <div class="row row-cols-1 row-cols-md-3 g-4 mt-4  justify-content-center">
    <% @categories.each do |category|%>
        <div class="card m-1" style="width: 22rem; height: 45rem;">
        <%= link_to products_products_path(category: category.id), style: "text-decoration: none;" do %>
        <% if category.images.attached? %>
          <%= image_tag category.images.first, class:"card-img-top", size:"400x500"%>
        <% end %>
        <div class="card-body">
        <h5 class="card-title text-dark"><%= category.name %></h5>
        <br>
        <h5 class="card-title text-dark"><%= category.desc %></h5>
        <%= link_to "Show Product",products_products_path(category: category.id), class:"btn btn-outline-success justify-content-center d-flex"%>
        <% end %>
        </div>
    </div>
    <% end %>
    </div>

app/views/products/new.html.erb
<%= render "form", product: @product %>

app/views/products/product.html.erb
<% if @category %>
  <% if @category.products.present? %>
    <div class="row row-cols-1 row-cols-md-3 g-4 mt-4 justify-content-center">
      <% @products.each do |product| %>
        <div class="card m-1" style="width: 25rem; height: 34rem;">
          <%= link_to product_path(product), style: "text-decoration: none;" do %>
            <% if product.images.attached? %>
              <%= image_tag product.images.first, class: "card-img-top", size: "350x350" %>
            <% end %>
            <div class="card-body">
              <h5 class="card-title text-dark"><%= product.name %></h5>
              <div class="text-dark">
                <strong>Price:</strong> &nbsp <%= number_to_currency(product.price, unit: "₹", format: "%u %n") %><br><br>
              </div>
              <%= link_to "Show Product", product_path(product), class: "btn btn-outline-success justify-content-center d-flex" %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  <% elsif %>
  <div class="md-3 mt-20 d-flex justify-content-around align-items-center"><h3> Sorry There is no products for this Category.</h3></div>
  <% end %> 
<% else%>
<% if current_user.admin? %>
<%= link_to "New Product", new_product_path , class:"btn btn-primary", style:"text-decoration: none;"%>
<% end %><br><br>
<% if current_user.guest? %>
  <div class="d-flex justify-content-end">
  <div class="search-form-container">
    <%= form_tag(products_products_path(category: @category), method: "get") do %>
      <%= select_tag(:category, options_for_select(Category.pluck(:name, :id), params[:category]), include_blank: "Select category", class: "search-form-input")%>
      <%= submit_tag("Filter") %>
    <% end %>
  </div>
  </div>
<% if @category %>
  <% if @category.products.present? %>
    <div class="row row-cols-1 row-cols-md-3 g-4 mt-4 justify-content-center">
      <% @products.each do |product| %>
        <div class="card m-1" style="width: 25rem; height: 34rem;">
          <%= link_to product_path(product), style: "text-decoration: none;" do %>
            <% if product.images.attached? %>
              <%= image_tag product.images.first, class: "card-img-top", size: "350x350" %>
            <% end %>
            <div class="card-body">
              <h5 class="card-title text-dark"><%= product.name %></h5>
              <div class="text-dark">
                <strong>Price:</strong> &nbsp <%= number_to_currency(product.price, unit: "₹", format: "%u %n") %><br><br>
              </div>
              <%= link_to "Show Product", product_path(product), class: "btn btn-outline-success justify-content-center d-flex" %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  <% else %>
    <h1>No products found for category: <%= params[:category] %></h1>
  <% end %>
  <% end %>
<% end %>
<br>
<div class="row row-cols-1 row-cols-md-3 g-4 justify-content-center" id="product-list">
<%= render partial: 'product_batch', locals: { products: @products.take(10) } %>
</div>
<br>
<div class="d-flex justify-content-center">
<button id="load-more-btn" class="btn btn-secondary btn-lg">Load More</button>
</div>
<% end %>


<script>
  $(document).ready(function() {
    var Page = 1;
    console.log(Page);

    function loadNextBatch() {
      Page++;
      console.log(Page);
      $.ajax({
        url: '<%= products_products_products_path %>',
        type: 'GET',
        dataType: 'html',
        data: { page: Page },
        success: function(data) {
          $('#product-list').append(data); 
        }
      });
    }

   
    $('#load-more-btn').click(function() {
      loadNextBatch();
    });
  });
</script>

app/views/products/show.html.erb
<div class="d-flex justify-content-end">
     
<%= link_to products_path do %>
 <%= image_tag "back-button.png",size:"60x60", alt: "Logo" %>
<% end %>
</div>
<div class="container">
  <div class="row">
    <div class="col-sm-9 col-md-3 col-lg mx-auto">
      <div class="card my-5 shadow">
        <div class="card-body">
          <div class="row">
          <div class="d-flex justify-content-center">         
          <div class="container mt-3 backroung-light">
          <div class="row">
          <div class="col-md-5">
                <div id="carouselExampleFade" class="carousel slide carousel-fade">
                  <div class="carousel-inner" style="height:100%;">
                   <% (0...@product.images.count).each do |image| %>
                    <div class="carousel-item active">
                    <%= image_tag(@product.images[1], class:"d-block w-100",size:"400x500") %>
                    </div>
                    <div class="carousel-item">
                    <%= image_tag(@product.images[0],class:"d-block w-100",size:"400x500") %>
                    </div>
                    <div class="carousel-item">
                    <%= image_tag(@product.images[2],class:"d-block w-100",size:"400x500") %>
                    </div>
                    <% end %>
                  </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>
          </div>
          <div class="col-md-4 style="font-size:21px;" ">
            <h2><%= @product.name %></h2><br>
            <strong>Product Description:</strong> &nbsp <%= @product.desc %><br>
            <strong>Sizes:</strong> &nbsp <%= @product.sizes.pluck(:name).join(', ') %><br>
            <strong>Price:</strong> &nbsp <%= number_to_currency(@product.price, unit: "₹", format: "%u %n") %><br>
            <p><strong>Available Quantity:</strong> &nbsp <%= @total_quantity %> items.</p><br>
            </div>
          <div class="col-md-3">
          <%= render partial: 'sizes', locals: { sizes: @product.sizes } %>
          <%= form_with(model: Lineitem.new, url: lineitems_path, method: :post) do |form| %>
            <%= hidden_field_tag :product_id, @product.id %>
            <% if user_signed_in? %>
            <%= hidden_field_tag :user_id, current_user.id %>
            <% end %>
            <div class="field">
              <strong>Sizes:<strong>
              <div class="size-buttons">
              <% @product.sizes.each do |size| %>
                <button class="size-button" id="size_<%= size.id %>" type="button" data-size-id="<%= size.id %>">
                  <%= size.abbreviation %>
                </button>
              <% end %>
              </div>
              <%= hidden_field_tag :size_ids, nil, id: "size_ids" %>
            </div>
              <%= label_tag "Quantity" %>
              <%= number_field_tag "quantity" %><br><br>
              <%= form.submit "Add to Cart", class: "btn btn-primary" %>
            </div><br>
          <% end %>
          </div>
          </div>
          </div>
          
          <br>
          <% if current_user.present? && current_user.admin? %>
          <%= link_to "Edit", edit_product_path, class:"btn btn-outline-success" %>
          <%= link_to 'Destroy', product_path(@product), method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
          <% end %>
                </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <hr>
        <% if current_user.present? && current_user.admin? %>
        <%= link_to new_product_similar_product_path(@product), as:"Add Related Products" do %>
        <h5><%= image_tag "https://cdn-icons-png.flaticon.com/128/3416/3416075.png",size:"30x30", alt: "Logo" %>
        <%= link_to "Add Related Product", new_product_similar_product_path(@product), class:"style:font-size:21px; text-dark",style:"text-decoration: none;" %></h5>
        <% end %>
        <% end %>
        <br>
        <h2>Similar Products</h2>
        <% if @similar_products.any? %>
        <br>
        <div id="similar-products-carousel" class="justify-content-center">
  <% @product.similar_products.each do |similar_product| %>
    <div class="card m-1">
      <%= link_to product_similar_product_path(@product, similar_product), style: "text-decoration: none;" do %>
        <% if similar_product.images.attached? %>
          <%= image_tag similar_product.images.first, class: "card-img-top ratio ratio-1x1" ,style:"height:500px;"%>
        <% end %>
        <div class="card-body">
          <h5 class="card-title text-dark"><%= similar_product.name %></h5>
          <div class="text-dark">
            <strong>Price:</strong> &nbsp <%= number_to_currency(similar_product.price, unit: "₹", format: "%u %n") %><br>
            <strong>Size:</strong> &nbsp <%= similar_product.size %>
          </div>
          <%= link_to "Show Product", product_similar_product_path(@product, similar_product), class: "btn btn-outline-success justify-content-center d-flex" %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>
        <% end %> 


<script>
$(document).ready(function() {
$('.size-button').click(function() {
// Get the size ID from the data attribute
var sizeId = $(this).data('size-id');
// Set the value of the hidden input field for size_ids
$('#size_ids').val(sizeId);
});
});
</script>

<script type="text/javascript">
  $(document).ready(function(){
    $('#similar-products-carousel').slick({
      autoplay: true,
  autoplaySpeed: 1000,
  slidesToShow: 4, // Number of slides to show initially
  responsive: [
    {
      breakpoint: 992,
      settings: {
        slidesToShow: 3
      }
    },
    {
      breakpoint: 576,
      settings: {
        slidesToShow: 2
      }
    }
  ],
  swipeToSlide: true, // Enables swiping/dragging to navigate between slides
  speed: 500
    });
  });
</script>